services:
  oauth-api-prod:
    image: ghcr.io/andipiee/go-oidc:latest
    env_file: .env.prod
    networks:
      - infra-private-net
    restart: unless-stopped
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

networks:
  infra-private-net:
    external: true
